package com.kaizenmobile.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AppStatsAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAppStatsAllPropertiesEquals(AppStats expected, AppStats actual) {
        assertAppStatsAutoGeneratedPropertiesEquals(expected, actual);
        assertAppStatsAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAppStatsAllUpdatablePropertiesEquals(AppStats expected, AppStats actual) {
        assertAppStatsUpdatableFieldsEquals(expected, actual);
        assertAppStatsUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAppStatsAutoGeneratedPropertiesEquals(AppStats expected, AppStats actual) {
        assertThat(expected)
            .as("Verify AppStats auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAppStatsUpdatableFieldsEquals(AppStats expected, AppStats actual) {
        assertThat(expected)
            .as("Verify AppStats relevant properties")
            .satisfies(e -> assertThat(e.getUsedTenantId()).as("check usedTenantId").isEqualTo(actual.getUsedTenantId()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAppStatsUpdatableRelationshipsEquals(AppStats expected, AppStats actual) {}
}
